name: gen_locale
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: '>=3.0.0 <=4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  analyzer: ">=3.0.0 <7.0.0"
  mason_logger: ">=0.2.14 <0.3.1"
  string_literal_finder:
    git:
      url: https://github.com/nemr0/string_literal_finder.git
      path: packages/string_literal_finder
  yaml: ^3.1.2
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  glob: ^2.1.2
  path: ^1.9.0
  
executables:
  genlocale:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
